### ISSUE TITLE
Infografia Topicos

### ISSUE THREAD

**Issue by JazminloRI** [SistemasTecTlaxiaco/infografia-de-las-librerias-JazminloRI#2]
[INFOGRAFIA JAZMIN LOPEZ RIVEROS topicos.pdf](https://github.com/SistemasTecTlaxiaco/infografia-de-las-librerias-JazminloRI/files/6307927/INFOGRAFIA.JAZMIN.LOPEZ.RIVEROS.topicos.pdf)

**Comment by Yeim1129** [comment]
Evaluacion: 16.0%
Evaluò: Josè Manuel Hernàndez

**Comment by josealfredo79** [comment]
esta bien hecho y revisado.
